cookie:
  expiry_days: 30
  key: thermoteq_cookie_key
  name: thermoteq_login_cookie
credentials:
  usernames:
    admin:
      email: admin@thermoteq.com
      name: Admin
      password: $2b$12$zNZFmVDLq/YX0YiaWyTbSeudZOB743YzIATR679fC0juOkMWGncr6
      role: admin
    gerald:
      email: gerald@thermoteq.com
      name: Gerald
      password: $2b$12$ZcaCi5yYy2N70qbiUoOe4ObNEhrw40sktWmSZCBm8JNf.4dDArzke
      role: user
preauthorized:
- admin@thermoteq.com
